### ISSUE TITLE
maven-plugin-support library not found.

### ISSUE THREAD

**Issue by hanrw** [tacitknowledge/maven-atg-assembler-plugin#1]
i'm trying to using this plugin, but maven-plugin-support library is not aviliable.

**Comment by scottfromsf** [comment]
I wasn't aware that this plugin was even made public. I'll check to see what's blocking the Maven Plugin Support dependency from becoming public.

**Comment by hanrw** [comment]
So nice of you.

**Comment by scottfromsf** [comment]
We've made the maven-plugin-support public (see https://github.com/tacitknowledge/maven-plugin-support) and have pushed 1.0.1 out to Maven Central. You should be good to go now.

**Comment by hanrw** [comment]
i have tried.but it seems not work. could you tell me more details about how to config the pom and project structure.
Thank you.
